### PR TITLE
Issue15: Implement CMV condition 13

### PR DESCRIPTION
**Pull request by MercuriaL01**
feat: added CMV13 and a test for it. Also added a test for the helper function isInsideCircle which is used for CMV13.

### CODE REVIEW

**Review by VinterSallad — CHANGES_REQUESTED** [review]
Make sure that the for loop condition does not check for values outside of the array, I think in this case since you have "<=", if we assume 5 points, we are going to check 0,2,4, but will also check 1,3,5 which is technically out of bounds since 5 is the 6th NUMPOINT even though we are assuming 5.

I am not sure about the purpose of including the print line code here except for testing.

Also I think you have misinterpreted condition 13, it wants you to look for 3 points that do not fit within a circle of radius1 and 3 points that do fit within a circle with radius2, they do not have to be the same 3 points meaning if you find 3 points that do fit within radius2, you are now only looking for 3 points to do not fit within radius1 etc.

Also we already have a helper function for this that takes 3 points and outputs the smallest possible radius for a circle to fit these 3 points, use this one instead and compare with radius1 and radius2.

**Comment by VinterSallad** [comment]
The helper function is called smallestRadius, takes 3 points, and returns smallest radius that incorporates these 3 points.

**Comment by MercuriaL01** [comment]
> Make sure that the for loop condition does not check for values outside of the array, I think in this case since you have "<=", if we assume 5 points, we are going to check 0,2,4, but will also check 1,3,5 which is technically out of bounds since 5 is the 6th NUMPOINT even though we are assuming 5.
> 
> I am not sure about the purpose of including the print line code here except for testing.
> 
> Also I think you have misinterpreted condition 13, it wants you to look for 3 points that do not fit within a circle of radius1 and 3 points that do fit within a circle with radius2, they do not have to be the same 3 points meaning if you find 3 points that do fit within radius2, you are now only looking for 3 points to do not fit within radius1 etc.
> 
> Also we already have a helper function for this that takes 3 points and outputs the smallest possible radius for a circle to fit these 3 points, use this one instead and compare with radius1 and radius2.

You are correct I misunderstood the question and fixed so the radius1 and radius2 checks can be for different sets of points. The print was also just for testing purposes as you mentioned and I missed to remove it. I also changed the indexing after further thinking about it and realizing you are correct. Now it should be fixed

**Review by VinterSallad — APPROVED** [review]
Looks good now

**Pull request merged**
