### PR TITLE
Issue/11: Implement CMV condition 9

### PR DESCRIPTION
**Pull request by MercuriaL01**
feat: added the code for both CMV9 and the test for it. Ran the test successfully.

### CODE REVIEW

**Comment by VinterSallad** [comment]
don't forget test cases for the helper function

**Review by VinterSallad — CHANGES_REQUESTED** [review]
Add some tests for the helper function angleBetweenPoints to make sure it is correct, otherwise the rest looks sensible.

**Comment by MercuriaL01** [comment]
> Add some tests for the helper function angleBetweenPoints to make sure it is correct, otherwise the rest looks sensible.

I added a test now and it seems to be working correctly.

**Review by MercuriaL01 — COMMENTED** [review]
I added a test now and it seems to be working correctly.

**Pull request merged**
